version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

workflows:
  test-build-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only:
                - main
                - prod
      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only: prod

jobs:
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Run tests
          command: npm ci && npm run testCI
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit
            JEST_JUNIT_UNIQUE_OUTPUT_NAME: "true"
      - store_test_results:
          path: ./reports/junit
      - store_artifacts:
          path: ./reports/junit

  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm install && NODE_OPTIONS=--openssl-legacy-provider npm run build

