version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

workflows:
  test-build-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only: prod

jobs:
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm ci && npm run test

  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm install && npm run build

